# Site settings
title: Tweetie JR Sabado
name: Tweetie JR Sabado

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/twetesaturday
 - title: LinkedIn
   url: https://www.linkedin.com/in/twetesaturday/
   
#Any buzzword skills you want to include
skills:
 - CSS3
 - SCSS
 - HTML5
 - SQL
 - VB.Net
 - Salesforcee
 - Javascript
 - NodeJS
 - AngularJS
 - Angular
 - Java
 - SQL
 - REST
 - API Design
 - PHP
 - Codeigniter
 - Git
 - Bootstrap
 - Typescript
 - JIRA
 - Azure Devops
 - Visual Studio Code
 - Mocha
 - Sinon
 - Chai
 
#Work experience is required
roles:
 - title: Application <br/>Development Analyst
   start: 2017
   end: ongoing
   employer: Accenture
   description: Responsible for the development of web portal for one of Accenture's diamond clients. <br/> Pioneered Accenture's web portal for client schedules and agenda builder.
 - title: Research and Development PHP Developer
   start: 2016
   end: 2017
   employer: Gameloft
   description: Spearheaded code revamp projects, introduced new functions, and assisted fellow developers in implementation of a new tech infrastructure.
 - title: Software <br/> Development Engineer
   start: 2014
   end: 2016
   employer: Allied Telesis Labs, Inc.
   description: Developed Next Generation Firewall - UI for the company's switches and routers using MongoDB, ExpressJS, AngularJS and NodeJS(MEAN Stack) and Bootstrap. Used Git for the Version Control System.

#Education is required
education:
 - level: Bachelor of Science
   date: 2014
   subject: Information Systems
   school: University of Santo Tomas

#This section is optional (as is the image link below)
coursera:
   courses:
    - title: Asphalt Xtreme
      link: http://asphaltxtreme.com
    - title:  Iron Blade
      link: http://www.ironbladegame.com
    - title:  Disney Magic Kingdoms
      link: http://www.disney-magic-kingdoms.com

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
speakerdeck:
   talks:
    - title: Web Development 
      conference: Design your future, UST (University of Santo Tomas) April 2017
      
intro: |
  Hello. I'm Tweetie. You can call me Tweets. A technophile and a passionate web developer with a knack for creating software solutions that aims to help the community. <br/><br/>
  I have a solid experience of almost 5 years and I continue to sharpen and update my skills through online courses.  <br/><br/>
  I want to inspire women in Technology while aiming to gain exposure and credibility in this industry as well as honing my skills in leadership and management. 

theme: jekyll-theme-cayman
